package org.apache.jsp.html.portal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.germinus.easyconf.Filter;
import com.liferay.lock.DuplicateLockException;
import com.liferay.lock.model.Lock;
import com.liferay.lock.service.LockServiceUtil;
import com.liferay.portal.NoSuchUserException;
import com.liferay.portal.captcha.CaptchaTextException;
import com.liferay.portal.kernel.cal.Recurrence;
import com.liferay.portal.kernel.dao.DAOParamUtil;
import com.liferay.portal.kernel.dao.search.ResultRow;
import com.liferay.portal.kernel.dao.search.RowChecker;
import com.liferay.portal.kernel.dao.search.SearchContainer;
import com.liferay.portal.kernel.dao.search.SearchEntry;
import com.liferay.portal.kernel.dao.search.TextSearchEntry;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.language.LanguageWrapper;
import com.liferay.portal.kernel.language.UnicodeLanguageUtil;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.log.LogUtil;
import com.liferay.portal.kernel.portlet.LiferayPortletMode;
import com.liferay.portal.kernel.portlet.LiferayWindowState;
import com.liferay.portal.kernel.security.permission.ActionKeys;
import com.liferay.portal.kernel.security.permission.PermissionChecker;
import com.liferay.portal.kernel.servlet.BrowserSniffer;
import com.liferay.portal.kernel.util.ArrayUtil;
import com.liferay.portal.kernel.util.BooleanWrapper;
import com.liferay.portal.kernel.util.CalendarFactoryUtil;
import com.liferay.portal.kernel.util.Constants;
import com.liferay.portal.kernel.util.ContentTypes;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.IntegerWrapper;
import com.liferay.portal.kernel.util.JavaConstants;
import com.liferay.portal.kernel.util.KeyValuePair;
import com.liferay.portal.kernel.util.KeyValuePairComparator;
import com.liferay.portal.kernel.util.ObjectValuePair;
import com.liferay.portal.kernel.util.ObjectValuePairComparator;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.OrderedProperties;
import com.liferay.portal.kernel.util.ParamUtil;
import com.liferay.portal.kernel.util.PrefsParamUtil;
import com.liferay.portal.kernel.util.PropertiesUtil;
import com.liferay.portal.kernel.util.Randomizer;
import com.liferay.portal.kernel.util.ServerDetector;
import com.liferay.portal.kernel.util.SortedProperties;
import com.liferay.portal.kernel.util.StackTraceUtil;
import com.liferay.portal.kernel.util.StringComparator;
import com.liferay.portal.kernel.util.StringMaker;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.UnicodeFormatter;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.language.LanguageImpl;
import com.liferay.portal.lucene.LuceneFields;
import com.liferay.portal.model.*;
import com.liferay.portal.model.impl.*;
import com.liferay.portal.security.auth.PrincipalException;
import com.liferay.portal.service.*;
import com.liferay.portal.service.impl.LayoutTemplateLocalUtil;
import com.liferay.portal.service.permission.LayoutPermissionUtil;
import com.liferay.portal.service.permission.PortletPermissionUtil;
import com.liferay.portal.struts.StrutsUtil;
import com.liferay.portal.theme.PortletDisplay;
import com.liferay.portal.theme.ThemeDisplay;
import com.liferay.portal.util.ContentUtil;
import com.liferay.portal.util.CookieKeys;
import com.liferay.portal.util.DateFormats;
import com.liferay.portal.util.PortalUtil;
import com.liferay.portal.util.PortletKeys;
import com.liferay.portal.util.PrefsPropsUtil;
import com.liferay.portal.util.PropsUtil;
import com.liferay.portal.util.Recipient;
import com.liferay.portal.util.ReleaseInfo;
import com.liferay.portal.util.SessionClicks;
import com.liferay.portal.util.SessionTreeJSClicks;
import com.liferay.portal.util.ShutdownUtil;
import com.liferay.portal.util.WebAppPool;
import com.liferay.portal.util.WebKeys;
import com.liferay.portal.util.comparator.RecipientComparator;
import com.liferay.portal.util.comparator.PortletCategoryComparator;
import com.liferay.portal.util.comparator.PortletTitleComparator;
import com.liferay.portlet.CachePortlet;
import com.liferay.portlet.PortalPreferences;
import com.liferay.portlet.PortletConfigFactory;
import com.liferay.portlet.PortletConfigImpl;
import com.liferay.portlet.PortletInstanceFactory;
import com.liferay.portlet.PortletPreferencesFactoryUtil;
import com.liferay.portlet.PortletSetupUtil;
import com.liferay.portlet.PortletURLImpl;
import com.liferay.portlet.PortletURLUtil;
import com.liferay.portlet.RenderParametersPool;
import com.liferay.portlet.RenderRequestFactory;
import com.liferay.portlet.RenderRequestImpl;
import com.liferay.portlet.RenderResponseFactory;
import com.liferay.portlet.RenderResponseImpl;
import com.liferay.portlet.UserAttributes;
import com.liferay.portlet.messaging.util.MessagingUtil;
import com.liferay.portlet.portletconfiguration.util.PortletConfigurationUtil;
import com.liferay.util.BeanParamUtil;
import com.liferay.util.BeanUtil;
import com.liferay.util.CollectionFactory;
import com.liferay.util.CookieUtil;
import com.liferay.util.CreditCard;
import com.liferay.util.FileUtil;
import com.liferay.util.Html;
import com.liferay.util.Http;
import com.liferay.util.HttpUtil;
import com.liferay.util.JS;
import com.liferay.util.ListUtil;
import com.liferay.util.LocaleUtil;
import com.liferay.util.MathUtil;
import com.liferay.util.PKParser;
import com.liferay.util.PwdGenerator;
import com.liferay.util.SetUtil;
import com.liferay.util.State;
import com.liferay.util.StateUtil;
import com.liferay.util.TextFormatter;
import com.liferay.util.Time;
import com.liferay.util.cal.CalendarUtil;
import com.liferay.util.dao.hibernate.QueryUtil;
import com.liferay.util.format.PhoneNumberUtil;
import com.liferay.util.log4j.Levels;
import com.liferay.util.mail.InternetAddressUtil;
import com.liferay.util.portlet.DynamicRenderRequest;
import com.liferay.util.servlet.DynamicServletRequest;
import com.liferay.util.servlet.SessionErrors;
import com.liferay.util.servlet.SessionMessages;
import com.liferay.util.servlet.SessionParameters;
import com.liferay.util.servlet.StringServletResponse;
import com.liferay.util.servlet.UploadException;
import com.liferay.util.xml.XMLFormatter;
import java.io.ByteArrayInputStream;
import java.io.StringReader;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collection;
import java.util.Collections;
import java.util.Currency;
import java.util.Date;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.Stack;
import java.util.TimeZone;
import java.util.TreeMap;
import java.util.TreeSet;
import javax.portlet.PortletConfig;
import javax.portlet.PortletContext;
import javax.portlet.PortletException;
import javax.portlet.PortletMode;
import javax.portlet.PortletPreferences;
import javax.portlet.PortletSession;
import javax.portlet.PortletURL;
import javax.portlet.RenderRequest;
import javax.portlet.RenderResponse;
import javax.portlet.UnavailableException;
import javax.portlet.ValidatorException;
import javax.portlet.WindowState;
import org.apache.struts.Globals;
import org.json.JSONObject;
import com.ext.util.*;
import gnomon.business.StringUtils;
import gnomon.hibernate.model.views.ViewResult;
import com.liferay.portal.kernel.security.permission.ActionExtKeys;
import com.liferay.portal.CookieNotSupportedException;
import com.liferay.portal.LayoutFriendlyURLException;
import com.liferay.portal.LayoutHiddenException;
import com.liferay.portal.LayoutNameException;
import com.liferay.portal.LayoutParentLayoutIdException;
import com.liferay.portal.LayoutPermissionException;
import com.liferay.portal.LayoutTypeException;
import com.liferay.portal.NoSuchResourceException;
import com.liferay.portal.NoSuchUserException;
import com.liferay.portal.PortletActiveException;
import com.liferay.portal.RequiredLayoutException;
import com.liferay.portal.RequiredRoleException;
import com.liferay.portal.SendPasswordException;
import com.liferay.portal.UserActiveException;
import com.liferay.portal.UserEmailAddressException;
import com.liferay.portal.UserLockoutException;
import com.liferay.portal.UserPasswordException;
import com.liferay.portal.UserScreenNameException;
import com.liferay.portal.action.LoginAction;
import com.liferay.portal.security.auth.AuthException;
import com.liferay.portal.service.impl.ThemeLocalUtil;
import com.liferay.portal.service.permission.GroupPermissionUtil;
import com.liferay.portal.service.permission.LocationPermissionUtil;
import com.liferay.portal.service.permission.OrganizationPermissionUtil;
import com.liferay.portal.struts.PortletRequestProcessor;
import com.liferay.portal.util.LayoutLister;
import com.liferay.portal.util.LayoutView;
import com.liferay.portal.util.OpenIdUtil;
import com.liferay.portlet.journalcontent.util.JournalContentUtil;
import com.liferay.portlet.layoutconfiguration.util.RuntimePortletUtil;
import com.liferay.util.servlet.fileupload.LiferayFileUpload;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.taglib.tiles.ComponentConstants;
import org.apache.struts.tiles.ComponentDefinition;
import org.apache.struts.tiles.TilesUtil;
import org.openid4java.association.AssociationException;
import org.openid4java.consumer.ConsumerException;
import org.openid4java.discovery.DiscoveryException;
import org.openid4java.message.MessageException;

public final class css_005fcached_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(25);
    _jspx_dependants.add("/html/portal/init.jsp");
    _jspx_dependants.add("/html/common/init.jsp");
    _jspx_dependants.add("/WEB-INF/tld/displaytag.tld");
    _jspx_dependants.add("/WEB-INF/tld/easyconf.tld");
    _jspx_dependants.add("/WEB-INF/tld/c-rt.tld");
    _jspx_dependants.add("/WEB-INF/tld/fmt-rt.tld");
    _jspx_dependants.add("/WEB-INF/tld/sql-rt.tld");
    _jspx_dependants.add("/WEB-INF/tld/x-rt.tld");
    _jspx_dependants.add("/WEB-INF/tld/liferay-portlet.tld");
    _jspx_dependants.add("/WEB-INF/tld/liferay-portlet-ext.tld");
    _jspx_dependants.add("/WEB-INF/tld/liferay-security.tld");
    _jspx_dependants.add("/WEB-INF/tld/liferay-theme.tld");
    _jspx_dependants.add("/WEB-INF/tld/liferay-ui.tld");
    _jspx_dependants.add("/WEB-INF/tld/liferay-util.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-bean.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-bean-el.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-html.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-html-el.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-logic.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-logic-el.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-nested.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-tiles.tld");
    _jspx_dependants.add("/WEB-INF/tld/struts-tiles-el.tld");
    _jspx_dependants.add("/html/common/init-ext.jsp");
    _jspx_dependants.add("/html/portal/css_cached_uniform.jsp");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


/**
 * Copyright (c) 2000-2007 Liferay, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

      out.write("\r\n");
      out.write("\r\n");

/**
 * Copyright (c) 2000-2007 Liferay, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

      out.write('\n');
      out.write('\n');

/**
 * Copyright (c) 2000-2007 Liferay, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  liferay-theme:defineObjects
      com.liferay.taglib.theme.DefineObjectsTag _jspx_th_liferay_002dtheme_005fdefineObjects_005f0 = (com.liferay.taglib.theme.DefineObjectsTag) _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.get(com.liferay.taglib.theme.DefineObjectsTag.class);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_liferay_002dtheme_005fdefineObjects_005f0 = _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.reuse(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.reuse(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
      com.liferay.portal.theme.ThemeDisplay themeDisplay = null;
      com.liferay.portal.model.Company company = null;
      com.liferay.portal.model.Account account = null;
      com.liferay.portal.model.User user = null;
      com.liferay.portal.model.User realUser = null;
      com.liferay.portal.model.Contact contact = null;
      com.liferay.portal.model.Layout layout = null;
      java.util.List layouts = null;
      java.lang.Long plid = null;
      com.liferay.portal.model.LayoutTypePortlet layoutTypePortlet = null;
      java.lang.Long portletGroupId = null;
      com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker = null;
      java.util.Locale locale = null;
      java.util.TimeZone timeZone = null;
      com.liferay.portal.model.Theme theme = null;
      com.liferay.portal.model.ColorScheme colorScheme = null;
      com.liferay.portal.theme.PortletDisplay portletDisplay = null;
      themeDisplay = (com.liferay.portal.theme.ThemeDisplay) _jspx_page_context.findAttribute("themeDisplay");
      company = (com.liferay.portal.model.Company) _jspx_page_context.findAttribute("company");
      account = (com.liferay.portal.model.Account) _jspx_page_context.findAttribute("account");
      user = (com.liferay.portal.model.User) _jspx_page_context.findAttribute("user");
      realUser = (com.liferay.portal.model.User) _jspx_page_context.findAttribute("realUser");
      contact = (com.liferay.portal.model.Contact) _jspx_page_context.findAttribute("contact");
      layout = (com.liferay.portal.model.Layout) _jspx_page_context.findAttribute("layout");
      layouts = (java.util.List) _jspx_page_context.findAttribute("layouts");
      plid = (java.lang.Long) _jspx_page_context.findAttribute("plid");
      layoutTypePortlet = (com.liferay.portal.model.LayoutTypePortlet) _jspx_page_context.findAttribute("layoutTypePortlet");
      portletGroupId = (java.lang.Long) _jspx_page_context.findAttribute("portletGroupId");
      permissionChecker = (com.liferay.portal.kernel.security.permission.PermissionChecker) _jspx_page_context.findAttribute("permissionChecker");
      locale = (java.util.Locale) _jspx_page_context.findAttribute("locale");
      timeZone = (java.util.TimeZone) _jspx_page_context.findAttribute("timeZone");
      theme = (com.liferay.portal.model.Theme) _jspx_page_context.findAttribute("theme");
      colorScheme = (com.liferay.portal.model.ColorScheme) _jspx_page_context.findAttribute("colorScheme");
      portletDisplay = (com.liferay.portal.theme.PortletDisplay) _jspx_page_context.findAttribute("portletDisplay");
      out.write("\r\n");
      out.write("\r\n");

/**
 * Copyright (c) 2000-2006 Liferay, LLC. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
//@ page import="com.liferay.portal.kernel.util.PortletExtKeys" 
      out.write("\r\n");
      out.write("\r\n");




String contextPath = PropsUtil.get(PropsUtil.PORTAL_CTX);
if (contextPath.equals("/")) {
	contextPath = "";
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");

response.setContentType(ContentTypes.TEXT_CSS);

      out.write("\r\n");
      out.write("\r\n");

/**
 * Copyright (c) 2000-2007 Liferay, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" ---------- Uni-Form form controls ----------\r\n");
      out.write("Uni-Form (v1.1) by Dragan Babic  - http://dnevnikeklektika.com/uni-form/\r\n");
      out.write("\r\n");
      out.write("Modified to use the Liferay/JSR-168 classname convention\r\n");
      out.write("Regex used to convert classnames are\r\n");
      out.write("Find: (\\.|#)([a-z]+)([A-Z]{1})([a-z]+)(\\s|\\{|:|,)\r\n");
      out.write("Replace: $1$2-\\L$3$4$5\r\n");
      out.write("\r\n");
      out.write("Distributed under http://creativecommons.org/licenses/by-sa/2.5/\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write(".uni-form {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Some generals */\r\n");
      out.write("\r\n");
      out.write(".uni-form .ctrl-holder {\r\n");
      out.write("\t/* this is the main unit that contains our form elements */\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .button-holder {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .reset-button {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .submit-button {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-label,   .uni-form .inline-labels .inline-label,   .uni-form .block-labels .inline-label {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tmargin: 0 1em 0 0;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-label input {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .focused {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ########################################################################## */\r\n");
      out.write("/* Styles for form controls where labels are in line with the input elements */\r\n");
      out.write("/* Set the class of the parent (preferably to a fieldset) to .inline-labels */\r\n");
      out.write(".uni-form .inline-labels .ctrl-holder {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels label,   .uni-form .inline-labels .label {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tline-height: 100%;\r\n");
      out.write("\tmargin: .3em 2% 0 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels .text-input,   .uni-form .inline-labels .file-upload {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels .file-upload {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels .select-input {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels textarea {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels .form-hint {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* inlineLabels esthetics */\r\n");
      out.write(".uni-form .inline-labels .form-hint strong {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ########################################################################## */\r\n");
      out.write("/* Styles for form controls where labels are above the input elements */\r\n");
      out.write("/* Set the class of the parent (preferably to a fieldset) to .block-labels */\r\n");
      out.write(".uni-form .block-labels .ctrl-holder {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels label,   .uni-form .block-labels .label {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tline-height: 100%;\r\n");
      out.write("\tmargin: .3em 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .label {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 3em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .inline-label {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: .15em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .text-input,   .uni-form .block-labels .file-upload {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .file-upload {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .select-input {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels textarea {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .form-hint {\r\n");
      out.write("\tclear: none;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* blockLabels esthetics */\r\n");
      out.write(".uni-form .block-labels .ctrl-holder {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .focused {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ########################################################################## */\r\n");
      out.write("/* Focus pseudoclasses */\r\n");
      out.write(".uni-form .ctrl-holder .text-input:focus {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form div.focused .text-input:focus {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form div.focused .form-hint {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Required fields asterisk styling, use if needed */\r\n");
      out.write(".uni-form label em,   .uni-form .label em {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tleft: 100%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels label em,   .uni-form .block-labels .label em {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tposition: static;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ########################################################################## */\r\n");
      out.write("/* Messages */\r\n");
      out.write(".uni-form #error-msg,   .uni-form .error {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg dt,   .uni-form #error-msg h3 {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg dd {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg ol {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg ol li {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .error-field {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ########################################################################## */\r\n");
      out.write("/* Add the following classes to your fieldsets (preferably) if you want columns */\r\n");
      out.write(".uni-form .col {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .column-left {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .column-right {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- IE Specific controls ---------- */\r\n");
      out.write("\r\n");
      out.write(".ie6 .uni-form,   .ie6 .uni-form fieldset,   .ie6 .ctrl-holder,   .ie6 .ctrl-holder span,   .ie6 .form-hint {\r\n");
      out.write("\t/* trigger haslayout, move to your ie specific stylesheet if possible */\r\n");
      out.write("\tzoom: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6 .block-labels .form-hint {\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Uni-Form custom rules ---------- */\r\n");
      out.write("/* Your styles below */\r\n");
      out.write("/* Keep in mind that wherever you see \"Required property\" it means that the property must exist, adjust it's value to your liking */\r\n");
      out.write("/* Generals */\r\n");
      out.write(".uni-form fieldset {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form fieldset legend {\r\n");
      out.write("\t/* reset ie */\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-size: 120%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .ctrl-holder {\r\n");
      out.write("\t/* this is the main unit that contains our form elements */\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .button-holder {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tmargin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .ctrl-holder .button-holder {\r\n");
      out.write("\tclear: none;\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .focused {\r\n");
      out.write("\tbackground: #FFFCDF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .inline-labels */\r\n");
      out.write(".uni-form .inline-labels label,  .uni-form .inline-labels .label {\r\n");
      out.write("\twidth: 45%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels .text-input,  .uni-form .inline-labels .file-upload {\r\n");
      out.write("\twidth: 45%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels .select-input {\r\n");
      out.write("\twidth: 45%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels textarea {\r\n");
      out.write("\theight: 12em; /* required property */\r\n");
      out.write("\twidth: 45%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .inline-labels .form-hint {\r\n");
      out.write("\tmargin-left: 47%;\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .block-labels */\r\n");
      out.write(".uni-form .block-labels .text-input,  .uni-form .block-labels .file-upload {\r\n");
      out.write("\twidth: 53%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .select-input {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 53.5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels textarea {\r\n");
      out.write("\t/* required property */\r\n");
      out.write("\theight: 12em;\r\n");
      out.write("\twidth: 53%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .block-labels .form-hint {\r\n");
      out.write("\twidth: 45%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Columns */\r\n");
      out.write(".uni-form .col {\r\n");
      out.write("\tmargin: 0 2% 0 0; /* required property */\r\n");
      out.write("\twidth: 47.9%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .column-left {\r\n");
      out.write("\twidth: 49%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .column-right {\r\n");
      out.write("\twidth: 49%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Messages */\r\n");
      out.write(".uni-form #error-msg {\r\n");
      out.write("\tbackground: #FFDFDF;\r\n");
      out.write("\tborder: 1px solid #DF7D7D;\r\n");
      out.write("\tborder-width: 1px 0;\r\n");
      out.write("\tmargin: 0 0 1em 0;\r\n");
      out.write("\tpadding: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .error {\r\n");
      out.write("\tbackground: #FFDFDF;\r\n");
      out.write("\tborder: 1px solid #DF7D7D;\r\n");
      out.write("\tborder-width: 1px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg dt,  .uni-form #error-msg h3 {\r\n");
      out.write("\tfont-size: 110%;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tline-height: 100%;\r\n");
      out.write("\tmargin: 0 0 .5em 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg dd {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg ol {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form #error-msg ol li {\r\n");
      out.write("\tborder-bottom: 1px dotted #DF7D7D;\r\n");
      out.write("\tlist-style-position: inside;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 2px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uni-form .error-field {\r\n");
      out.write("\tbackground: #FFBFBF;\r\n");
      out.write("\tcolor: #AF4C4C;\r\n");
      out.write("\tmargin: 0 0 6px 0;\r\n");
      out.write("\tpadding: 4px;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* ---------- Modules ---------- */\r\n");
      out.write("\r\n");
      out.write("/* ---------- Add content styles ---------- */\r\n");
      out.write("\r\n");
      out.write(".portal-add-content-search {\r\n");
      out.write("\tmargin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portal-add-content img{\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portal-add-content table td{\r\n");
      out.write("\tpadding: 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portal-add-content table td{\r\n");
      out.write("\tpadding: 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portal-add-content table td:first-child, .portal-add-content table td.first-child {\r\n");
      out.write("\tpadding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portal-add-content table td:last-child, .portal-add-content table td.last-child {\r\n");
      out.write("\tpadding-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Color picker ---------- */\r\n");
      out.write("\r\n");
      out.write(".lfr-color-picker {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/color_picker/picker_container_bg.png);\r\n");
      out.write("\tfont-family: Arial,Helvetica,sans-serif;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\theight: 192px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 305px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-color {\r\n");
      out.write("\tbackground-color: #F00;\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/color_picker/picker_bg.png);\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\theight: 184px;\r\n");
      out.write("\tleft: 8px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 5px;\r\n");
      out.write("\twidth: 184px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-color-indic {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/color_picker/select.gif);\r\n");
      out.write("\theight: 11px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-hue {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/color_picker/hue.png);\r\n");
      out.write("\theight: 186px;\r\n");
      out.write("\tleft: 200px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 3px;\r\n");
      out.write("\twidth: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-hue-indic {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/color_picker/color_indic.gif);\r\n");
      out.write("\theight: 7px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-current-color {\r\n");
      out.write("\tborder: 2px solid #999;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("\ttop: 38px;\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-color-values {\r\n");
      out.write("\tleft: 240px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-color-values input {\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tpadding: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-old-color {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-rgbR, .lfr-rgbG, .lfr-rgbB {\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-hex {\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-color-picker-close {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/color_picker/close.png);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 5px;\r\n");
      out.write("\ttext-indent: -9999em;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Interactive Dock ---------- */\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmin-width: 150px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode h2 {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/menu_bar.png) no-repeat 100% -30px;\r\n");
      out.write("\tfont-size: 1.2em;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tpadding: 0 29px 0 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 82;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode h2 span {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/menu_bar.png) no-repeat 0 0;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfont-size: 1.2em;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tpadding: 0.5em 0.5em 0.5em 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.expanded .lfr-dock-list-container {\r\n");
      out.write("\tborder-top: none;\r\n");
      out.write("\ttop: -2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode ul {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/menu_bg.png) no-repeat 0 0;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode li {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tmargin-bottom: 0pt;\r\n");
      out.write("\tmargin-left: 0.2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode li a {\r\n");
      out.write("\tbackground-position: 0.5em 50%;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tborder-top: 1px solid #ccc;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-left: 0.3em;\r\n");
      out.write("\tpadding: 0.5em 0pt 0.5em 2.5em;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode ul.lfr-dock-list > li:first-child a, .js .lfr-dock.interactive-mode ul.lfr-dock-list > li:first-child ul.show-my-places li:first-child a {\r\n");
      out.write("\tborder-top: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode li a:hover {\r\n");
      out.write("\tbackground-position: 1.5em 50%;\r\n");
      out.write("\tpadding-left: 3.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode ul.lfr-dock-list > li:first-child a, .js .lfr-dock.interactive-mode ul.lfr-dock-list > li:first-child a:hover, .js .lfr-dock.interactive-mode ul.lfr-dock-list li.my-places ul.show-my-places li ul li:first-child a, .js .lfr-dock.interactive-mode ul.lfr-dock-list li.my-places ul.show-my-places li ul li:first-child a:hover {\r\n");
      out.write("\tborder-top: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .my-places {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode li.my-places li a {\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .lfr-dock.interactive-mode li.my-places li ul li.current a, .js .lfr-dock.interactive-mode li.my-places li ul li.current a:hover {\r\n");
      out.write("\tbackground: transparent url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/my_place_current.png) no-repeat 1em 50%;\r\n");
      out.write("\tmargin: 0.1em 0 0 0.2em;\r\n");
      out.write("\tpadding-left: 3.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmin-width: 200px;\r\n");
      out.write("\tpadding: 0.2em;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 85%;\r\n");
      out.write("\ttop: 87%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places.send-right .show-my-places {\r\n");
      out.write("\tleft: 100%;\r\n");
      out.write("\ttop: -10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places.send-down .show-my-places {\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li {\r\n");
      out.write("\tbackground: url() no-repeat 5px 50%;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li .my-places-toggle {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/my_place.png) no-repeat 3px 50%;\r\n");
      out.write("\tfont-size: 1.1em;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tpadding: 0.5em 0.2em 0.5em 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li .my-places-toggle h3 {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/expand_community.png) no-repeat 100% 50%;\r\n");
      out.write("\tpadding-right: 1.8em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li .my-places-toggle.hide h3 {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/collapse_community.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li ul {\r\n");
      out.write("\tbackground: none no-repeat 3px 50%;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li ul {\r\n");
      out.write("\tmargin-left: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li ul li {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places ul li.public a, .js .my-places .show-my-places ul li.public a:hover {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/my_places_public.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places li.private a, .js .my-places .show-my-places li.private a:hover {\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/my_places_private.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places ul li.public a.add-page, .js .interactive-mode .my-places .show-my-places ul li.private a.add-page {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/page_settings.png) no-repeat;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfont-size: 0;\r\n");
      out.write("\theight: 16px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 3px;\r\n");
      out.write("\ttext-indent: -9999em;\r\n");
      out.write("\ttop: 3px;\r\n");
      out.write("\twidth: 16px;\r\n");
      out.write("}\r\n");
      out.write(".js .interactive-mode .my-places .show-my-places ul li.public a.add-page:hover, .js .interactive-mode .my-places .show-my-places ul li.private a.add-page:hover {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/dock/page_settings.png) no-repeat;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6.js .lfr-dock.interactive-mode {\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie.js .lfr-dock .my-places .show-my-places h3 {\r\n");
      out.write("\tfont-size: 1.1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6.js .lfr-dock.expanded.interactive-mode .lfr-dock-list-container {\r\n");
      out.write("\theight: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6.js .interactive-mode .my-places .show-my-places {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6.js .lfr-dock.interactive-mode li {\r\n");
      out.write("\theight: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6.js .lfr-dock.interactive-mode li a {\r\n");
      out.write("\theight: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Portlet css editor ---------- */\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties .uni-form {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties fieldset {\r\n");
      out.write("\tmargin-bototm: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties fieldset fieldset {\r\n");
      out.write("\tmargin-top: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties fieldset fieldset legend {\r\n");
      out.write("\tfont-size: 1.1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties .uni-form .text-input {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties .uni-form fieldset.col {\r\n");
      out.write("\twidth: 29%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties .common {\r\n");
      out.write("\twidth: 27%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties .extra {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties #lfr-border-width, #portlet-set-properties #lfr-border-style, #portlet-set-properties #lfr-border-color {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties #lfr-border-width {\r\n");
      out.write("\twidth: 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties #lfr-border-style {\r\n");
      out.write("\twidth: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties #lfr-border-color {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties #lfr-padding, #portlet-set-properties #lfr-margin {\r\n");
      out.write("\twidth: 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties .uni-form #custom-css {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("#portlet-set-properties .form-hint {\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("}\r\n");
      out.write("#portlet-set-properties .lfr-bg-image-properties {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("#portlet-set-properties #border-note {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portlet-set-properties .uni-form {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Tree ---------- */\r\n");
      out.write("\r\n");
      out.write("ul.gamma {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma .expand-image {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li {\r\n");
      out.write("\tmargin-bottom: 2px;\r\n");
      out.write("\tpadding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li ul {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li ul li, ul.gamma li.tree-item {\r\n");
      out.write("\tpadding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma img {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li.tree-item {\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li.tree-item a img {\r\n");
      out.write("\tcursor: move;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li.tree-item li {\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li.tree-item ul {\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma li.tree-item a, ul.gamma li.tree-item .expand-image {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.gamma .tree-item-hover {\r\n");
      out.write("\tbackground: #7D93C1;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".toggle-expand {\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".toggle-expand a {\r\n");
      out.write("\tpadding: 2px 0 2px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lfr-expand {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/trees/expand_all.png) no-repeat 0 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lfr-collapse {\r\n");
      out.write("\tbackground: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/trees/collapse_all.png) no-repeat 0 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Portal ---------- */\r\n");
      out.write("\r\n");
      out.write("/* ---------- Generic styling ---------- */\r\n");
      out.write("\r\n");
      out.write(".popup-alert-notice, .popup-alert-warning {\r\n");
      out.write("\tbackground: #ffc url() no-repeat 5px 50%;\r\n");
      out.write("\tborder-bottom: 1px solid;\r\n");
      out.write("\tfont-size: 1.1em;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tpadding-left: 25px;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tz-index: 10000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-alert-notice {\r\n");
      out.write("\tbackground-color: #ffc;\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/messages/alert.gif);\r\n");
      out.write("\tborder-bottom-color: #fc0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-alert-warning {\r\n");
      out.write("\tbackground-color: #fcc;\r\n");
      out.write("\tbackground-image: url(");
      out.print( themeDisplay.getPathThemeImages() );
      out.write("/messages/error.gif);\r\n");
      out.write("\tborder-bottom-color: #f00;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6 .popup-alert-notice, .ie6 .popup-alert-warning {\r\n");
      out.write("\tbottom: auto;\r\n");
      out.write("  \tleft: expression( ( LFR_IGNORE_ME2 = document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft ) + 'px' );\r\n");
      out.write("  \tposition: absolute;\r\n");
      out.write("\tright: auto;\r\n");
      out.write("\ttop: expression( ( LFR_IGNORE_ME = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop ) + 'px' );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-alert-notice .countdown-timer {\r\n");
      out.write("\tfont-size: 1.1em;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Portlets ---------- */\r\n");
      out.write("\r\n");
      out.write("/* ---------- Generic styling ---------- */\r\n");
      out.write("\r\n");
      out.write(".breadcrumbs {\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liferay-table {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liferay-table tr td, .liferay-table tr th {\r\n");
      out.write("\tpadding: 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liferay-table tr th {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liferay-table tr td:first-child, .liferay-table tr td.first-child, .liferay-table tr th:first-child, .liferay-table tr th.first-child {\r\n");
      out.write("\tpadding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liferay-table tr td:last-child, .liferay-table tr td.last-child, .liferay-table tr th:last-child, .liferay-table tr th.last-child {\r\n");
      out.write("\tpadding-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lfr-control-links a {\r\n");
      out.write("\tmargin-right: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Liferay forms ---------- */\r\n");
      out.write("\r\n");
      out.write(".liferay-input-text {\r\n");
      out.write("\twidth: ");
      out.print( ModelHintsDefaults.TEXT_DISPLAY_WIDTH );
      out.write("px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liferay-textarea {\r\n");
      out.write("\theight: ");
      out.print( ModelHintsDefaults.TEXTAREA_DISPLAY_HEIGHT );
      out.write("px;\r\n");
      out.write("\twidth: ");
      out.print( ModelHintsDefaults.TEXTAREA_DISPLAY_WIDTH );
      out.write("px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Separator ---------- */\r\n");
      out.write("\r\n");
      out.write(".separator {\r\n");
      out.write("\tmargin: 15px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Taglib discussion thread ---------- */\r\n");
      out.write("\r\n");
      out.write(".taglib-discussion td img {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Taglib search iterator ---------- */\r\n");
      out.write("\r\n");
      out.write(".taglib-search-iterator {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".taglib-search-iterator td {\r\n");
      out.write("\tpadding: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- Specific portlet styles ---------- */\r\n");
      out.write("\r\n");
      out.write("/* ---------- Quick note ---------- */\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note {\r\n");
      out.write("\tmargin: 2px;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note textarea {\r\n");
      out.write("\tmin-height: 100px;\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\twidth: 95%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6 .portlet-quick-note textarea {\r\n");
      out.write("\theight: expression(this.height < 100 ? '100px' : this.height);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note .note-color {\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tfont-size: 0;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("\tmargin: 3px 5px;\r\n");
      out.write("\twidth: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note .note-color.yellow {\r\n");
      out.write("\tbackground-color: #ffc;\r\n");
      out.write("\tborder-color: #fc0;\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note .note-color.green {\r\n");
      out.write("\tbackground-color: #cfc;\r\n");
      out.write("\tborder-color: #0c0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note .note-color.blue {\r\n");
      out.write("\tbackground-color: #ccf;\r\n");
      out.write("\tborder-color: #309;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note .note-color.red {\r\n");
      out.write("\tbackground-color: #fcc;\r\n");
      out.write("\tborder-color: #f00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".portlet-quick-note a.close-note {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------- jQuery plugins ---------- */\r\n");
      out.write("\r\n");
      out.write("/* ---------- Tabs ---------- */\r\n");
      out.write("\r\n");
      out.write(".tabs-hide {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6 .tabs-nav {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6 .tabs-nav .tabs-disabled a {\r\n");
      out.write("\tfilter: alpha(opacity=40);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ----------- OpenID ---------- */\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"].openid_login {\r\n");
      out.write("   background: url(http://openid.net/login-bg.gif) no-repeat;\r\n");
      out.write("   background-color: #fff;\r\n");
      out.write("   background-position: 0 50%;\r\n");
      out.write("   color: #000;\r\n");
      out.write("   padding-left: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ie6 input.text.openid_login {\r\n");
      out.write("\tbackground: url(http://openid.net/login-bg.gif) no-repeat;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tbackground-position: 0 50%;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tpadding-left: 18px;\r\n");
      out.write("}");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
